services:
  frontend:
    build: ./frontend_incidencias
    container_name: frontend_incidencias
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend_incidencias
    container_name: backend_incidencias
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_incidencias
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: db_incidencias
    ports:
      - "3306:3306"

